services:
  random-api-go:
    container_name: random-api-go
    image: woodchen/random-api-go:latest
    ports:
      - "5003:5003"
    volumes:
      - ./data:/root/data
    environment:
      - TZ=Asia/Shanghai
      - BASE_URL=https://random-api.czl.net
      - OAUTH_CLIENT_ID=1234567890
      - OAUTH_CLIENT_SECRET=1234567890
    restart: unless-stopped
