services:
  random-api-go:
    container_name: random-api-go
    image: woodchen/random-api-go:latest
    ports:
      - "5003:5003"
    volumes:
      - ./public:/root/public
      - ./logs:/var/log/random-api
      - ./data:/root/data
    environment:
      - TZ=Asia/Shanghai
      - BASE_URL=https://example.com/csvfile
    restart: unless-stopped