name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE_NAME: random-api-go

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: woodchen
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: woodchen/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64


      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 拉取镜像
            docker pull woodchen/random-api-go:latest

            # 停止并删除容器
            docker stop random-api-go || true
            docker rm random-api-go || true

            # 启动容器
            docker compose -f /opt/1panel/docker/compose/random-api-go/docker-compose.yml up -d